In [ ]:
import pandas as pd
import numpy as np
import gensim
from random import sample

In [ ]:
# Load data
train_chal= pd.read_csv('/content/drive/My Drive/Colab Notebooks/RNN/train.csv')
test_chal = pd.read_csv('/content/drive/My Drive/Colab Notebooks/RNN/test.csv')
chall_details= pd.read_csv('/content/drive/My Drive/Colab Notebooks/RNN/challenge_data.csv')

In [ ]:
train=train_chal.groupby('user_id').challenge.apply(lambda x: ' '.join(x)).reset_index()
test=test_chal.groupby('user_id').challenge.apply(lambda x: ' '.join(x)).reset_index()
set(train.user_id).intersection(test.user_id)

set()

In [ ]:
train.shape, test.shape

((69532, 2), (39732, 2))

In [ ]:
sentence_list=pd.concat((train.challenge,test.challenge)).apply(lambda x: x.split())
# sentence_list= train.challenge.apply(lambda x: x.split())

In [ ]:
# train word2vec model to learn embeddings
'''neg=15
itera=200
window=5
size=500
print ('doing_'+str(neg)+'_'+str(window)+'_'+str(itera))
model=gensim.models.Word2Vec(sentence_list,size=size,window=window,workers=8,min_count=0, hs=1,iter=itera,sg=1)
model.save('word2vec_solved_iter')'''

"neg=15\nitera=200\nwindow=5\nsize=500\nprint ('doing_'+str(neg)+'_'+str(window)+'_'+str(itera))\nmodel=gensim.models.Word2Vec(sentence_list,size=size,window=window,workers=8,min_count=0, hs=1,iter=itera,sg=1)\nmodel.save('word2vec_solved_iter')"

In [ ]:
model= gensim.models.Word2Vec.load('/content/drive/My Drive/Colab Notebooks/RNN/word2vec_solved_iter__noshuf_5window_100_size_500')
model.most_similar('CI23855')

/usr/local/lib/python3.6/dist-packages/smart_open/smart_open_lib.py:253: UserWarning: This function is deprecated, use smart_open.open instead. See the migration notes for details: https://github.com/RaRe-Technologies/smart_open/blob/master/README.rst#migrating-to-the-new-open-function
  'See the migration notes for details: %s' % _MIGRATION_NOTES_URL
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: Call to deprecated `most_similar` (Method will be removed in 4.0.0, use self.wv.most_similar() instead).
  
/usr/local/lib/python3.6/dist-packages/gensim/matutils.py:737: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if np.issubdtype(vec.dtype, np.int):


[('CI23663', 0.36745941638946533),
 ('CI23975', 0.31903666257858276),
 ('CI23933', 0.31583738327026367),
 ('CI23913', 0.2977244257926941),
 ('CI25135', 0.2900288701057434),
 ('CI23714', 0.2872004508972168),
 ('CI24915', 0.2844502329826355),
 ('CI24917', 0.2660750150680542),
 ('CI24958', 0.2638528645038605),
 ('CI24527', 0.2628430724143982)]

In [ ]:
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation , Flatten
from keras.layers import TimeDistributed, concatenate, Bidirectional, Masking, RepeatVector
from keras.layers.embeddings import Embedding
from keras.layers.recurrent import LSTM, GRU, SimpleRNN
from keras.layers.convolutional import Convolution1D, MaxPooling1D


In [ ]:
pretrained_weights = model.wv.syn0
vocab_size, emdedding_size = pretrained_weights.shape
print('Result embedding shape:', pretrained_weights.shape)

Result embedding shape: (5502, 500)


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `syn0` (Attribute will be removed in 4.0.0, use self.wv.vectors instead).
  """Entry point for launching an IPython kernel.


In [ ]:
def word2idx(word):
  return model.wv.vocab[word].index
def idx2word(idx):
  return model.wv.index2word[idx]

In [ ]:
# generate int sequences for challenge sentences
train_seq=np.array(train.challenge.apply(lambda x: x.split()).apply(lambda x: ([(word2idx(y)) for y in x])).tolist())
test_seq=np.array(test.challenge.apply(lambda x: x.split()).apply(lambda x: ([(word2idx(y)) for y in x])).tolist())
print('train:',train_seq.shape)
print('------------------')
print('test:',test_seq.shape)
print('------------------')
print('train:',train_seq)
print('------------------')
print('test:',test_seq)

train: (69532, 13)
------------------
test: (39732, 10)
------------------
train: [[   1    0    2 ...    4   36    8]
 [   3    0    5 ...   13  101   33]
 [ 209  260  228 ...  340  233  188]
 ...
 [  60  143   33 ...   68  524  802]
 [  48    5   58 ...  351  464 1170]
 [  13  143  246 ... 2499 1270 2247]]
------------------
test: [[  0   5   2 ...   6 101   7]
 [  3   0   2 ...  13   4  93]
 [369 702 549 ... 595 479 266]
 ...
 [  5 123  29 ... 699 468  68]
 [  3 123 143 ... 299 387   6]
 [ 12   5  83 ...   1   7  62]]


In [ ]:
xtrain=train_seq[:,:10]
ytrain= train_seq[:,10]
xtrain.shape, ytrain.shape
print('xtrain:',xtrain.shape)
print('------------------')
print('ytrain:',ytrain.shape)
print('------------------')
print('train:',xtrain)
print('------------------')
print('ytrain:',ytrain)

xtrain: (69532, 10)
------------------
ytrain: (69532,)
------------------
train: [[   1    0    2 ...   10   13   35]
 [   3    0    5 ...   93   36    6]
 [ 209  260  228 ...  210  179  202]
 ...
 [  60  143   33 ...  212  305    8]
 [  48    5   58 ...   11  151  620]
 [  13  143  246 ... 2817  205  166]]
------------------
ytrain: [   4   13  340 ...   68  351 2499]


In [ ]:
# add 11th,12th,13th challenge to outcome
xtrain= np.concatenate((xtrain,xtrain,xtrain),axis=0)
ytrain= np.concatenate((train_seq[:,10],train_seq[:,11],train_seq[:,12]))
print('xtrain:',xtrain.shape)
print('------------------')
print('ytrain:',ytrain.shape)
print('------------------')
print('train:',xtrain)
print('------------------')
print('ytrain:',ytrain)

xtrain: (208596, 10)
------------------
ytrain: (208596,)
------------------
train: [[   1    0    2 ...   10   13   35]
 [   3    0    5 ...   93   36    6]
 [ 209  260  228 ...  210  179  202]
 ...
 [  60  143   33 ...  212  305    8]
 [  48    5   58 ...   11  151  620]
 [  13  143  246 ... 2817  205  166]]
------------------
ytrain: [   4   13  340 ...  802 1170 2247]


In [ ]:
# define nn model
from keras.layers import Embedding
emdedding_size=500
vocab_size=5502
keras_model2 = Sequential()
keras_model2.add(Embedding(input_dim=vocab_size, output_dim=emdedding_size, 
                    weights=[pretrained_weights]))
keras_model2.add(GRU(units=emdedding_size)) #,return_sequences=True
#keras_model2.add(Bidirectional(GRU(units=emdedding_size)))
#keras_model2.add(Dropout(0.2))
keras_model2.add(Dense(units=vocab_size))
keras_model2.add(Activation('softmax'))
keras_model2.compile(optimizer='adam', loss='sparse_categorical_crossentropy',metrics = ['accuracy'])

In [ ]:
sample_weight=np.concatenate((np.ones(train.shape[0])*3,np.ones(train.shape[0])*2,np.ones(train.shape[0])))

In [ ]:
# fit differnt samples of data and then full data
keras_model2.fit(xtrain,ytrain, epochs=4, sample_weight=sample_weight,
          batch_size=512, verbose=1,validation_split=0.11)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/indexed_slices.py:434: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "


Train on 185650 samples, validate on 22946 samples
Epoch 1/4
185650/185650 [==============================] - 515s 3ms/step - loss: 11.6765 - accuracy: 0.0367 - val_loss: 5.4356 - val_accuracy: 0.0269
Epoch 2/4
185650/185650 [==============================] - 513s 3ms/step - loss: 9.7072 - accuracy: 0.0653 - val_loss: 5.1769 - val_accuracy: 0.0346
Epoch 3/4
185650/185650 [==============================] - 509s 3ms/step - loss: 8.8594 - accuracy: 0.0916 - val_loss: 5.1098 - val_accuracy: 0.0367
Epoch 4/4
185650/185650 [==============================] - 513s 3ms/step - loss: 8.1184 - accuracy: 0.1184 - val_loss: 5.1488 - val_accuracy: 0.0393


In [ ]:
keras_model2.fit(xtrain,ytrain, epochs=3, sample_weight=sample_weight,
          batch_size=512, verbose=1,validation_split=0.11)

Train on 185650 samples, validate on 22946 samples
Epoch 1/3
185650/185650 [==============================] - 517s 3ms/step - loss: 7.4546 - accuracy: 0.1444 - val_loss: 5.2389 - val_accuracy: 0.0317
Epoch 2/3
185650/185650 [==============================] - 525s 3ms/step - loss: 6.8510 - accuracy: 0.1712 - val_loss: 5.3547 - val_accuracy: 0.0292
Epoch 3/3
185650/185650 [==============================] - 523s 3ms/step - loss: 6.3251 - accuracy: 0.1923 - val_loss: 5.5132 - val_accuracy: 0.0238


In [ ]:
keras_model2.fit(xtrain,ytrain, epochs=2, sample_weight=sample_weight,
          batch_size=256, verbose=1,validation_split=0.11)

Train on 185650 samples, validate on 22946 samples
Epoch 1/2
185650/185650 [==============================] - 603s 3ms/step - loss: 6.4978 - accuracy: 0.1795 - val_loss: 5.7602 - val_accuracy: 0.0217
Epoch 2/2
185650/185650 [==============================] - 598s 3ms/step - loss: 5.8192 - accuracy: 0.2081 - val_loss: 5.9972 - val_accuracy: 0.0150


In [ ]:
keras_model2.fit(xtrain,ytrain, epochs=1, sample_weight=sample_weight,
          batch_size=512, verbose=1)#saurabhmodel-4

Epoch 1/1
208596/208596 [==============================] - 564s 3ms/step - loss: 4.6650 - accuracy: 0.2293


In [ ]:
keras_model2.fit(xtrain,ytrain, epochs=1, sample_weight=sample_weight,
          batch_size=512, verbose=1)#saurabhmodel-6

Epoch 1/1
208596/208596 [==============================] - 567s 3ms/step - loss: 4.5171 - accuracy: 0.2267


In [ ]:
keras_model2.fit(xtrain,ytrain, epochs=1, sample_weight=sample_weight,
          batch_size=512, verbose=1)#saurabhmodel-7

Epoch 1/1
208596/208596 [==============================] - 571s 3ms/step - loss: 4.4018 - accuracy: 0.2261


In [ ]:
# fit differnt samples of data and then full data
keras_model2.fit(xtrain,ytrain, epochs=4, sample_weight=sample_weight,
          batch_size=512, verbose=1,validation_split=0.11)

In [ ]:
import pickle
pickle.dump(keras_model2.to_json(),open('gru7.pkl','wb'))

In [ ]:
import h5py
import keras
# from importlib import reload
# import keras
keras_model2.save_weights('gru7.weights')

In [ ]:
#test.challenge.values[0]

In [ ]:
# generate_next('CI23855 CI23933 CI24917 CI24915 CI23714 CI23663 CI24958 CI25135 CI25727 CI24530')

In [ ]:
test_inds=np.array(test.challenge.apply(lambda x: np.array([word2idx(word) for word in x.split()])).tolist())
test_inds.shape, xtrain.shape

((39732, 10), (208596, 10))

In [ ]:
# make predictions
nnpred=keras_model2.predict(test_inds)
nnpred.shape

(39732, 5502)

In [ ]:
nnpred2= pd.Series(nnpred.argsort(axis=1)[:,-3:].tolist())

In [ ]:
# store to csv
count=0
test['pred']=nnpred2.apply(lambda x: [idx2word(y) for y in x[::-1]])
test_sub= test.copy()
test_sub=pd.concat((test_sub,test_sub,test_sub))
test_sub=test_sub.sort_values('user_id').reset_index(drop=True)
test_sub['seq']=test_sub.groupby('user_id').cumcount()
test_sub.seq= test_sub.seq+11
test_sub['user_sequence']= test_sub.user_id.astype('str') + '_' + test_sub.seq.astype('str')
test_sub['challenge']=test_sub.apply(lambda row: row['pred'][row['seq']-11], axis=1)
test_sub[['user_sequence','challenge']].to_csv('test7.csv',index=False)

In [ ]:
import pickle
pickle.dump(keras_model2.to_json(),open('/content/drive/My Drive/Colab Notebooks/RNN/gru7.pkl','wb'))

In [ ]:
import h5py
import keras
# from importlib import reload
# import keras
keras_model2.save_weights('/content/drive/My Drive/Colab Notebooks/RNN/gru7.weights')

In [ ]:
# store to csv
count=0
test['pred']=nnpred2.apply(lambda x: [idx2word(y) for y in x[::-1]])
test_sub= test.copy()
test_sub=pd.concat((test_sub,test_sub,test_sub))
test_sub=test_sub.sort_values('user_id').reset_index(drop=True)
test_sub['seq']=test_sub.groupby('user_id').cumcount()
test_sub.seq= test_sub.seq+11
test_sub['user_sequence']= test_sub.user_id.astype('str') + '_' + test_sub.seq.astype('str')
test_sub['challenge']=test_sub.apply(lambda row: row['pred'][row['seq']-11], axis=1)
test_sub[['user_sequence','challenge']].to_csv('/content/drive/My Drive/Colab Notebooks/RNN/saurabhmodel-7.csv',index=False)